// ResultsDashboard.tsx

import React from 'react';
import { FinancialReport } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import PptxGenJS from 'pptxgenjs';

interface ResultsDashboardProps {
  report: FinancialReport;
}

const formatCurrency = (value: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);

const formatNumber = (value: number) =>
  new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 }).format(value);

const ResultsDashboard: React.FC<ResultsDashboardProps> = ({ report }) => {
  const { metrics, executive_summary } = report;

  // Waterfall Comparison:
  // Stack 1 (Costs): Implementation (One-time) + Operational (Annual)
  // Stack 2 (Value): Labor Savings + Revenue Uplift
  const chartData = [
    {
      name: 'Year 1 Costs',
      implementation: report.inputs_used.one_time_implementation_cost_usd,
      operational: report.inputs_used.operational_cost_per_year_usd,
      savings: 0,
      revenue: 0,
    },
    {
      name: 'Year 1 Value',
      implementation: 0,
      operational: 0,
      savings: metrics.annual_cost_savings_usd,
      revenue: metrics.projected_revenue_uplift_usd,
    }
  ];

  const handleExportSlide = () => {
    try {
        if (!report.metrics.pptx_data_structure) {
            alert("PPTX data not available in this report version.");
            return;
        }

        const pres = new PptxGenJS();
        const pptxData = report.metrics.pptx_data_structure;
        
        // --- Single Executive Slide Generation ---
        const slide = pres.addSlide();
        
        // 1. Title Section (Top)
        // Background strip for title
        slide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 1.0, fill: { color: 'F1F5F9' } });
        
        // Main Title
        slide.addText(pptxData.slide_title, { 
            x: 0.3, y: 0.2, w: '90%', fontSize: 28, fontFace: 'Arial', color: pptxData.theme_colors.green.replace('#', ''), bold: true 
        });
        
        // Subtitle
        slide.addText(`Strategic ROI Analysis for ${report.inputs_used.ai_use_case}`, { 
            x: 0.3, y: 0.65, w: '90%', fontSize: 14, fontFace: 'Arial', color: '64748B'
        });

        // 2. Key Metrics Row (Middle)
        // Iterate through the key metrics provided by Gemini
        const metricCount = pptxData.key_metrics.length;
        const startX = 0.5;
        const totalW = 9.0;
        const gap = 0.2;
        const boxW = (totalW - (gap * (metricCount - 1))) / metricCount;

        pptxData.key_metrics.forEach((metric, index) => {
             const xPos = startX + (index * (boxW + gap));
             
             // Box background
             slide.addShape(pres.ShapeType.rect, { 
                 x: xPos, y: 1.5, w: boxW, h: 1.5, 
                 fill: { color: 'FFFFFF' }, 
                 line: { color: 'E2E8F0', width: 1 } 
             });

             // Label
             slide.addText(metric.label, {
                 x: xPos + 0.1, y: 1.6, w: boxW - 0.2, h: 0.3,
                 fontSize: 12, color: '64748B', align: 'center'
             });

             // Value
             slide.addText(metric.value, {
                 x: xPos + 0.1, y: 2.0, w: boxW - 0.2, h: 0.5,
                 fontSize: 24, bold: true, color: metric.color.replace('#', ''), align: 'center'
             });
        });

        // 3. Executive Summary / Bullet Points (Bottom)
        slide.addText('Strategic Recommendations & Impact:', {
            x: 0.5, y: 3.5, fontSize: 16, color: '1E293B', bold: true
        });

        const bulletPoints = pptxData.summary_bullet_points.map(point => ({
            text: point,
            options: { fontSize: 12, color: '334155', bullet: true, breakLine: true, paraSpaceBefore: 10 }
        }));

        slide.addText(bulletPoints, {
            x: 0.5, y: 3.8, w: 9.0, h: 2.5, valign: 'top'
        });

        // Footer
        slide.addText(`Generated on ${new Date().toLocaleDateString()} | AI ROI Analyst`, {
            x: 0.5, y: 5.2, fontSize: 10, color: '94A3B8', align: 'center'
        });

        pres.writeFile({ fileName: `Executive_ROI_Brief_${new Date().toISOString().split('T')[0]}.pptx` });

    } catch (e) {
        console.error("PPTX Generation Error", e);
        alert("Could not generate PPTX. Please check console.");
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="bg-white p-6 rounded-xl shadow-sm border-l-4 border-emerald-500">
        <h2 className="text-2xl font-bold text-slate-800">AI ROI Analyst Report</h2>
        <p className="text-slate-500 text-sm mt-1">Generated by Gemini AI Financial Analyst</p>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* ROI Card */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 flex flex-col justify-between">
            <div>
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider">Total ROI</p>
                <h3 className={`text-4xl font-bold mt-2 ${metrics.roi_percentage >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>
                {(metrics.roi_percentage * 100).toFixed(0)}%
                </h3>
            </div>
            <p className="text-xs text-slate-400 mt-4">Year 1 Return on Investment</p>
        </div>

        {/* Break Even Card */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 flex flex-col justify-between">
           <div>
               <p className="text-sm font-medium text-slate-500 uppercase tracking-wider">Break-Even Point</p>
               <h3 className="text-4xl font-bold text-blue-600 mt-2">
                 {formatNumber(metrics.break_even_point_months)}
                 <span className="text-lg text-slate-400 font-normal ml-1">months</span>
               </h3>
           </div>
           <p className="text-xs text-slate-400 mt-4">Time to recover implementation costs</p>
        </div>

        {/* Total Annual Hard Savings Card */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 flex flex-col justify-between">
            <div>
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider">Gross Annual Benefit</p>
                <h3 className="text-4xl font-bold text-emerald-600 mt-2">
                 {formatCurrency(metrics.total_annual_hard_savings_usd)}
                </h3>
            </div>
            <p className="text-xs text-slate-400 mt-4">Labor Savings + Revenue Uplift (Before Costs)</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Waterfall Chart */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 h-[400px] flex flex-col">
            <h3 className="text-lg font-semibold text-slate-800 mb-6">Cost vs. Value Breakdown (Year 1)</h3>
            <div className="flex-1 w-full">
                <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                    <XAxis
                        dataKey="name"
                        axisLine={false}
                        tickLine={false}
                        tick={{ fill: '#64748b', fontSize: 14 }}
                        dy={10}
                    />
                    <YAxis
                        axisLine={false}
                        tickLine={false}
                        tick={{ fill: '#64748b', fontSize: 12 }}
                        tickFormatter={(value) => `$${value / 1000}k`}
                    />
                    <Tooltip
                        cursor={{ fill: '#f1f5f9' }}
                        formatter={(value: number) => formatCurrency(value)}
                        contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                    />
                    <Legend iconType="circle" wrapperStyle={{ paddingTop: '20px' }} />
                    {/* Stack 1: Costs */}
                    <Bar dataKey="implementation" name="Implementation" stackId="a" fill="#ef4444" radius={[0, 0, 4, 4]} barSize={60} />
                    <Bar dataKey="operational" name="Operational Cost" stackId="a" fill="#f87171" radius={[4, 4, 0, 0]} barSize={60} />
                    
                    {/* Stack 2: Value */}
                    <Bar dataKey="savings" name="Labor Savings" stackId="a" fill="#10b981" radius={[0, 0, 4, 4]} barSize={60} />
                    <Bar dataKey="revenue" name="Revenue Uplift" stackId="a" fill="#34d399" radius={[4, 4, 0, 0]} barSize={60} />
                </BarChart>
                </ResponsiveContainer>
            </div>
        </div>

        {/* Soft ROI & Presentation Synthesis */}
        <div className="flex flex-col gap-6">
            {/* Soft ROI */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 flex-1">
                <h3 className="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-indigo-500" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 6a1 1 0 011-1h10a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V6zM3 10a1 1 0 001 1h12a1 1 0 100-2H4a1 1 0 00-1 1z" />
                        <path fillRule="evenodd" d="M3 14a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM4 17a1 1 0 00-1 1v1a1 1 0 001 1h12a1 1 0 001-1v-1a1 1 0 00-1-1H4z" clipRule="evenodd" />
                    </svg>
                    Strategic Value
                </h3>
                <div className="bg-indigo-50/50 p-4 rounded-lg border border-indigo-100">
                    <p className="text-slate-700 leading-relaxed text-sm">
                    {metrics.soft_roi_summary}
                    </p>
                </div>
                 <div className="mt-4 grid grid-cols-2 gap-4">
                    <div className="text-center p-3 bg-slate-50 rounded-lg">
                        <span className="block text-xs text-slate-400">Risk Mitigation</span>
                        <span className="font-bold text-slate-700 text-lg">{report.inputs_used.risk_mitigation_score_1_to_10}<span className="text-xs text-slate-400 font-normal">/10</span></span>
                    </div>
                    <div className="text-center p-3 bg-slate-50 rounded-lg">
                        <span className="block text-xs text-slate-400">Strategic Agility</span>
                        <span className="font-bold text-slate-700 text-lg">{report.inputs_used.strategic_agility_score_1_to_10}<span className="text-xs text-slate-400 font-normal">/10</span></span>
                    </div>
                </div>
            </div>

            {/* Presentation Recommendations */}
            <div className="bg-gradient-to-br from-slate-800 to-slate-900 p-6 rounded-xl shadow-md text-white">
                 <div className="flex justify-between items-center mb-4">
                    <h3 className="text-lg font-semibold flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-emerald-400" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z" />
                        </svg>
                        Executive Slide
                    </h3>
                    <button 
                        onClick={handleExportSlide}
                        className="text-xs bg-emerald-600 hover:bg-emerald-500 text-white px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1 border border-emerald-500 shadow-sm font-semibold"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        Export PPTX
                    </button>
                 </div>
                <ul className="space-y-3">
                    {metrics.slide_visual_recommendation.map((rec, index) => (
                        <li key={index} className="flex items-start gap-3 text-sm text-slate-300">
                            <span className="flex-shrink-0 w-5 h-5 bg-slate-700 rounded-full flex items-center justify-center text-xs font-bold text-white mt-0.5">{index + 1}</span>
                            <span>{rec}</span>
                        </li>
                    ))}
                </ul>
            </div>
        </div>
      </div>
    </div>
  );
};

export default ResultsDashboard;